# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BraintreeSwiftNodejs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BraintreeSwiftNodejs
pod 'BraintreeDropIn'
pod 'Braintree/PayPal'
pod 'Braintree/Venmo'
pod 'Braintree/Apple-Pay'
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.0'

end
